/*
 * Calamari API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * Contact: developers@calamari.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.thecodest.slack.holidayreminder.calamari.remote.api;

import com.thecodest.slack.holidayreminder.calamari.remote.api.model.CurrentShiftStatus;
import com.thecodest.slack.holidayreminder.calamari.remote.api.model.DailyPresenceReport;
import com.thecodest.slack.holidayreminder.calamari.remote.api.model.GetPresenceReportRequest;
import com.thecodest.slack.holidayreminder.calamari.remote.api.model.ShiftStatusRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.List;


/**
 * API tests for CurrentShiftStatusApi
 */
@Disabled
class CurrentShiftStatusApiTest {

	private final CurrentShiftStatusApi api = new CurrentShiftStatusApi();

	/**
	 * Get current shift status for all employees
	 * <p>
	 * Get current shift status for all employees.
	 *
	 * @throws Exception if the Api call fails
	 */
	@Test
	void getCurrentShiftStatusForAllTest() throws Exception {
		List<CurrentShiftStatus> response = api.getCurrentShiftStatusForAll();

		// TODO: test validations
	}

	/**
	 * Get current shift status for one person.
	 * <p>
	 * Get current shift status for one person.&lt;br /&gt;&lt;br /&gt;Expect error codes:&lt;ol&gt;&lt;li&gt;&lt;strong&gt;INVALID_EMPLOYEE&lt;/strong&gt; - when invalid employee id provided&lt;/li&gt;&lt;/ol&gt;
	 *
	 * @throws Exception if the Api call fails
	 */
	@Test
	void getCurrentShiftStatusForOnePersonTest() throws Exception {
		ShiftStatusRequest body = null;
		CurrentShiftStatus response = api.getCurrentShiftStatusForOnePerson(body);

		// TODO: test validations
	}

	/**
	 * Get current presence report for all employees
	 * <p>
	 * Get current presence report for all employees. Results are paged by employees number.&lt;br /&gt;&lt;br /&gt;Expect error codes:&lt;ol&gt;&lt;li&gt;&lt;strong&gt;INVALID_PAGE&lt;/strong&gt; - when invalid page provided&lt;/li&gt;&lt;li&gt;&lt;strong&gt;INVALID_LIMIT&lt;/strong&gt; - when invalid limit provided&lt;/li&gt;&lt;li&gt;&lt;strong&gt;INVALID_DATE_FROM&lt;/strong&gt; - when invalid date provided&lt;/li&gt;&lt;li&gt;&lt;strong&gt;INVALID_DATE_TO&lt;/strong&gt; - when invalid date provided&lt;/li&gt;
	 *
	 * @throws Exception if the Api call fails
	 */
	@Test
	void getPresenceReportTest() throws Exception {
		GetPresenceReportRequest body = null;
		List<DailyPresenceReport> response = api.getPresenceReport(body);

		// TODO: test validations
	}
}
