/*
 * Calamari API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * Contact: developers@calamari.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.thecodest.slack.holidayreminder.calamari.remote.api;

import com.thecodest.slack.holidayreminder.calamari.remote.api.model.CreatePositionIn;
import com.thecodest.slack.holidayreminder.calamari.remote.api.model.CreatePositionOut;
import com.thecodest.slack.holidayreminder.calamari.remote.api.model.PositionDto;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * API tests for PositionsApi
 */
@Disabled
class PositionsApiTest {

	private final PositionsApi api = new PositionsApi();

	/**
	 * Create a position.
	 * <p>
	 * Create a position.
	 *
	 * @throws Exception
	 *             if the Api call fails
	 */
	@Test
	void createPositionTest() throws Exception {
		CreatePositionIn body = null;
		CreatePositionOut response = api.createPosition(body);

		// TODO: test validations
	}

	/**
	 * Get all positions.
	 * <p>
	 * Get all positions.
	 *
	 * @throws Exception
	 *             if the Api call fails
	 */
	@Test
	void getPositionsTest() throws Exception {
		List<PositionDto> response = api.getPositions();

		// TODO: test validations
	}
}
