/*
 * Calamari API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * Contact: developers@calamari.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.thecodest.slack.holidayreminder.calamari.remote.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * BalanceEntryOut
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-06T15:14:15.923389380+02:00[Europe/Warsaw]")
public class BalanceEntryOut {
	@SerializedName("person")
	private EmployeeSimpleOut person = null;

	@SerializedName("balance")
	private Long balance = null;

	public BalanceEntryOut person(EmployeeSimpleOut person) {
		this.person = person;
		return this;
	}

	/**
	 * Get person
	 *
	 * @return person
	 **/
	@Schema(required = true, description = "")
	public EmployeeSimpleOut getPerson() {
		return person;
	}

	public void setPerson(EmployeeSimpleOut person) {
		this.person = person;
	}

	public BalanceEntryOut balance(Long balance) {
		this.balance = balance;
		return this;
	}

	/**
	 * Working time balance in seconds
	 *
	 * @return balance
	 **/
	@Schema(example = "-3600", required = true, description = "Working time balance in seconds")
	public Long getBalance() {
		return balance;
	}

	public void setBalance(Long balance) {
		this.balance = balance;
	}

	@Override
	public boolean equals(Object o) {
		if(this == o) {
			return true;
		}
		if(o == null || getClass() != o.getClass()) {
			return false;
		}
		BalanceEntryOut balanceEntryOut = (BalanceEntryOut) o;
		return Objects.equals(this.person, balanceEntryOut.person) && Objects.equals(this.balance, balanceEntryOut.balance);
	}

	@Override
	public int hashCode() {
		return Objects.hash(person, balance);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class BalanceEntryOut {\n");

		sb.append("    person: ").append(toIndentedString(person)).append("\n");
		sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if(o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
