/*
 * Calamari API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * Contact: developers@calamari.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.thecodest.slack.holidayreminder.calamari.remote.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.Objects;

/**
 * BreakOut
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-06T15:14:15.923389380+02:00[Europe/Warsaw]")
public class BreakOut {
	@SerializedName("person")
	private Person person = null;
	@SerializedName("breakStatus")
	private BreakStatusEnum breakStatus = null;

	public BreakOut person(Person person) {
		this.person = person;
		return this;
	}

	/**
	 * Get person
	 *
	 * @return person
	 **/
	@Schema(required = true, description = "")
	public Person getPerson() {
		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public BreakOut breakStatus(BreakStatusEnum breakStatus) {
		this.breakStatus = breakStatus;
		return this;
	}

	/**
	 * Employee break status after request
	 *
	 * @return breakStatus
	 **/
	@Schema(required = true, description = "Employee break status after request")
	public BreakStatusEnum getBreakStatus() {
		return breakStatus;
	}

	public void setBreakStatus(BreakStatusEnum breakStatus) {
		this.breakStatus = breakStatus;
	}

	@Override
	public boolean equals(Object o) {
		if(this == o) {
			return true;
		}
		if(o == null || getClass() != o.getClass()) {
			return false;
		}
		BreakOut breakOut = (BreakOut) o;
		return Objects.equals(this.person, breakOut.person) && Objects.equals(this.breakStatus, breakOut.breakStatus);
	}

	@Override
	public int hashCode() {
		return Objects.hash(person, breakStatus);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class BreakOut {\n");

		sb.append("    person: ").append(toIndentedString(person)).append("\n");
		sb.append("    breakStatus: ").append(toIndentedString(breakStatus)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if(o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Employee break status after request
	 */
	@JsonAdapter(BreakStatusEnum.Adapter.class)
	public enum BreakStatusEnum {
		STARTED("STARTED"), FINISHED("FINISHED");

		private String value;

		BreakStatusEnum(String value) {
			this.value = value;
		}

		public static BreakStatusEnum fromValue(String input) {
			for(BreakStatusEnum b : BreakStatusEnum.values()) {
				if(b.value.equals(input)) {
					return b;
				}
			}
			return null;
		}

		public String getValue() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}

		public static class Adapter extends TypeAdapter<BreakStatusEnum> {
			@Override
			public void write(final JsonWriter jsonWriter, final BreakStatusEnum enumeration) throws IOException {
				jsonWriter.value(String.valueOf(enumeration.getValue()));
			}

			@Override
			public BreakStatusEnum read(final JsonReader jsonReader) throws IOException {
				Object value = jsonReader.nextString();
				return BreakStatusEnum.fromValue((String) (value));
			}
		}
	}

}
