/*
 * Calamari API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * Contact: developers@calamari.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.thecodest.slack.holidayreminder.calamari.remote.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/**
 * Absence request comment with content and creator
 */
@Schema(description = "Absence request comment with content and creator")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-06T15:14:15.923389380+02:00[Europe/Warsaw]")
public class Comment {
	@SerializedName("creator")
	private String creator = null;

	@SerializedName("content")
	private String content = null;

	@SerializedName("absenceRequestId")
	private Long absenceRequestId = null;

	public Comment creator(String creator) {
		this.creator = creator;
		return this;
	}

	/**
	 * Employee identifier. You can use e-mail or external identifier in format (externalNumber:ABC123)
	 *
	 * @return creator
	 **/
	@Schema(example = "john.white@mycompany.com", required = true, description = "Employee identifier. You can use e-mail or external identifier in format (externalNumber:ABC123)")
	public String getCreator() {
		return creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Comment content(String content) {
		this.content = content;
		return this;
	}

	/**
	 * Comment content
	 *
	 * @return content
	 **/
	@Schema(example = "Home office", required = true, description = "Comment content")
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Comment absenceRequestId(Long absenceRequestId) {
		this.absenceRequestId = absenceRequestId;
		return this;
	}

	/**
	 * Absence request id
	 *
	 * @return absenceRequestId
	 **/
	@Schema(example = "12", required = true, description = "Absence request id")
	public Long getAbsenceRequestId() {
		return absenceRequestId;
	}

	public void setAbsenceRequestId(Long absenceRequestId) {
		this.absenceRequestId = absenceRequestId;
	}

	@Override
	public boolean equals(Object o) {
		if(this == o) {
			return true;
		}
		if(o == null || getClass() != o.getClass()) {
			return false;
		}
		Comment comment = (Comment) o;
		return Objects.equals(this.creator, comment.creator) && Objects.equals(this.content, comment.content) && Objects.equals(this.absenceRequestId, comment.absenceRequestId);
	}

	@Override
	public int hashCode() {
		return Objects.hash(creator, content, absenceRequestId);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Comment {\n");

		sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
		sb.append("    content: ").append(toIndentedString(content)).append("\n");
		sb.append("    absenceRequestId: ").append(toIndentedString(absenceRequestId)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if(o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
