/*
 * Calamari API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * Contact: developers@calamari.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.thecodest.slack.holidayreminder.calamari.remote.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CreateTeamIn
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-06T15:14:15.923389380+02:00[Europe/Warsaw]")
public class CreateTeamIn {
	@SerializedName("name")
	private String name = null;

	@SerializedName("members")
	private List<Long> members = new ArrayList<>();

	@SerializedName("managers")
	private List<Long> managers = new ArrayList<>();

	public CreateTeamIn name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * Team name.
	 *
	 * @return name
	 **/
	@Schema(example = "Marketing", required = true, description = "Team name.")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public CreateTeamIn members(List<Long> members) {
		this.members = members;
		return this;
	}

	public CreateTeamIn addMembersItem(Long membersItem) {
		this.members.add(membersItem);
		return this;
	}

	/**
	 * Identifiers of team members.
	 *
	 * @return members
	 **/
	@Schema(required = true, description = "Identifiers of team members.")
	public List<Long> getMembers() {
		return members;
	}

	public void setMembers(List<Long> members) {
		this.members = members;
	}

	public CreateTeamIn managers(List<Long> managers) {
		this.managers = managers;
		return this;
	}

	public CreateTeamIn addManagersItem(Long managersItem) {
		this.managers.add(managersItem);
		return this;
	}

	/**
	 * Identifiers of team managers.
	 *
	 * @return managers
	 **/
	@Schema(required = true, description = "Identifiers of team managers.")
	public List<Long> getManagers() {
		return managers;
	}

	public void setManagers(List<Long> managers) {
		this.managers = managers;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		CreateTeamIn createTeamIn = (CreateTeamIn) o;
		return Objects.equals(this.name, createTeamIn.name) && Objects.equals(this.members, createTeamIn.members)
				&& Objects.equals(this.managers, createTeamIn.managers);
	}

	@Override
	public int hashCode() {
		return Objects.hash(name, members, managers);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class CreateTeamIn {\n");

		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    members: ").append(toIndentedString(members)).append("\n");
		sb.append("    managers: ").append(toIndentedString(managers)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
