/*
 * Calamari API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * Contact: developers@calamari.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.thecodest.slack.holidayreminder.calamari.remote.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EmployeesOut
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-06T15:14:15.923389380+02:00[Europe/Warsaw]")
public class EmployeesOut {
	@SerializedName("employees")
	private List<EmployeeFullOut> employees = new ArrayList<>();

	@SerializedName("currentPage")
	private Integer currentPage = null;

	@SerializedName("totalPages")
	private Integer totalPages = null;

	public EmployeesOut employees(List<EmployeeFullOut> employees) {
		this.employees = employees;
		return this;
	}

	public EmployeesOut addEmployeesItem(EmployeeFullOut employeesItem) {
		this.employees.add(employeesItem);
		return this;
	}

	/**
	 * List of employees
	 *
	 * @return employees
	 **/
	@Schema(required = true, description = "List of employees")
	public List<EmployeeFullOut> getEmployees() {
		return employees;
	}

	public void setEmployees(List<EmployeeFullOut> employees) {
		this.employees = employees;
	}

	public EmployeesOut currentPage(Integer currentPage) {
		this.currentPage = currentPage;
		return this;
	}

	/**
	 * Current page
	 *
	 * @return currentPage
	 **/
	@Schema(required = true, description = "Current page")
	public Integer getCurrentPage() {
		return currentPage;
	}

	public void setCurrentPage(Integer currentPage) {
		this.currentPage = currentPage;
	}

	public EmployeesOut totalPages(Integer totalPages) {
		this.totalPages = totalPages;
		return this;
	}

	/**
	 * Total pages
	 *
	 * @return totalPages
	 **/
	@Schema(required = true, description = "Total pages")
	public Integer getTotalPages() {
		return totalPages;
	}

	public void setTotalPages(Integer totalPages) {
		this.totalPages = totalPages;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		EmployeesOut employeesOut = (EmployeesOut) o;
		return Objects.equals(this.employees, employeesOut.employees)
				&& Objects.equals(this.currentPage, employeesOut.currentPage)
				&& Objects.equals(this.totalPages, employeesOut.totalPages);
	}

	@Override
	public int hashCode() {
		return Objects.hash(employees, currentPage, totalPages);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class EmployeesOut {\n");

		sb.append("    employees: ").append(toIndentedString(employees)).append("\n");
		sb.append("    currentPage: ").append(toIndentedString(currentPage)).append("\n");
		sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
