/*
 * Calamari API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * Contact: developers@calamari.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.thecodest.slack.holidayreminder.calamari.remote.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Searching absence requests advanced filter.
 */
@Schema(description = "Searching absence requests advanced filter.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-06T15:14:15.923389380+02:00[Europe/Warsaw]")
public class FindAbsencesAdvancedIn {
	@SerializedName("from")
	private LocalDate from = null;

	@SerializedName("to")
	private LocalDate to = null;

	@SerializedName("absenceTypes")
	private List<String> absenceTypes = null;

	@SerializedName("teams")
	private List<String> teams = null;

	@SerializedName("positions")
	private List<String> positions = null;

	@SerializedName("contractTypes")
	private List<String> contractTypes = null;

	@SerializedName("employees")
	private List<String> employees = null;

	@SerializedName("createdFrom")
	private OffsetDateTime createdFrom = null;

	@SerializedName("createdTo")
	private OffsetDateTime createdTo = null;

	@SerializedName("updatedFrom")
	private OffsetDateTime updatedFrom = null;

	@SerializedName("updatedTo")
	private OffsetDateTime updatedTo = null;

	@SerializedName("absenceStatuses")
	private List<String> absenceStatuses = null;

	public FindAbsencesAdvancedIn from(LocalDate from) {
		this.from = from;
		return this;
	}

	/**
	 * Start date of dates range to search request in ISO format
	 *
	 * @return from
	 **/
	@Schema(example = "Tue Jan 10 01:00:00 CET 2017", required = true, description = "Start date of dates range to search request in ISO format")
	public LocalDate getFrom() {
		return from;
	}

	public void setFrom(LocalDate from) {
		this.from = from;
	}

	public FindAbsencesAdvancedIn to(LocalDate to) {
		this.to = to;
		return this;
	}

	/**
	 * End date of dates range to search request in ISO format
	 *
	 * @return to
	 **/
	@Schema(example = "Sun Jan 15 01:00:00 CET 2017", required = true, description = "End date of dates range to search request in ISO format")
	public LocalDate getTo() {
		return to;
	}

	public void setTo(LocalDate to) {
		this.to = to;
	}

	public FindAbsencesAdvancedIn absenceTypes(List<String> absenceTypes) {
		this.absenceTypes = absenceTypes;
		return this;
	}

	public FindAbsencesAdvancedIn addAbsenceTypesItem(String absenceTypesItem) {
		if (this.absenceTypes == null) {
			this.absenceTypes = new ArrayList<>();
		}
		this.absenceTypes.add(absenceTypesItem);
		return this;
	}

	/**
	 * List of absence types names or identifiers to search. Example: [\&quot;Annual
	 * Leave\&quot;, \&quot;Remote Work\&quot;, \&quot;Sick Leave\&quot;]
	 *
	 * @return absenceTypes
	 **/
	@Schema(description = "List of absence types names or identifiers to search. Example: [\"Annual Leave\", \"Remote Work\", \"Sick Leave\"]")
	public List<String> getAbsenceTypes() {
		return absenceTypes;
	}

	public void setAbsenceTypes(List<String> absenceTypes) {
		this.absenceTypes = absenceTypes;
	}

	public FindAbsencesAdvancedIn teams(List<String> teams) {
		this.teams = teams;
		return this;
	}

	public FindAbsencesAdvancedIn addTeamsItem(String teamsItem) {
		if (this.teams == null) {
			this.teams = new ArrayList<>();
		}
		this.teams.add(teamsItem);
		return this;
	}

	/**
	 * List of teams names or identifiers to search. As a result there will be
	 * absence requests of employees who are members of at least one of provided
	 * teams. Example: [\&quot;First Team\&quot;, \&quot;Second Team\&quot;,
	 * \&quot;Third Team\&quot;]
	 *
	 * @return teams
	 **/
	@Schema(description = "List of teams names or identifiers to search. As a result there will be absence requests of employees who are members of at least one of provided teams. Example: [\"First Team\", \"Second Team\", \"Third Team\"]")
	public List<String> getTeams() {
		return teams;
	}

	public void setTeams(List<String> teams) {
		this.teams = teams;
	}

	public FindAbsencesAdvancedIn positions(List<String> positions) {
		this.positions = positions;
		return this;
	}

	public FindAbsencesAdvancedIn addPositionsItem(String positionsItem) {
		if (this.positions == null) {
			this.positions = new ArrayList<>();
		}
		this.positions.add(positionsItem);
		return this;
	}

	/**
	 * List of positions names or identifiers to search. As a result there will be
	 * absence requests of employees who have one of provided positions. Example:
	 * [\&quot;Developer\&quot;, \&quot;Support\&quot;, \&quot;Architect\&quot;]
	 *
	 * @return positions
	 **/
	@Schema(description = "List of positions names or identifiers to search. As a result there will be absence requests of employees who have one of provided positions. Example: [\"Developer\", \"Support\", \"Architect\"]")
	public List<String> getPositions() {
		return positions;
	}

	public void setPositions(List<String> positions) {
		this.positions = positions;
	}

	public FindAbsencesAdvancedIn contractTypes(List<String> contractTypes) {
		this.contractTypes = contractTypes;
		return this;
	}

	public FindAbsencesAdvancedIn addContractTypesItem(String contractTypesItem) {
		if (this.contractTypes == null) {
			this.contractTypes = new ArrayList<>();
		}
		this.contractTypes.add(contractTypesItem);
		return this;
	}

	/**
	 * List of contract types names or identifiers to search. As a result there will
	 * be absence requests of employees who have one of contract type. Example:
	 * [\&quot;firstContract\&quot;, \&quot;secondContract\&quot;]
	 *
	 * @return contractTypes
	 **/
	@Schema(description = "List of contract types names or identifiers to search. As a result there will be absence requests of employees who have one of contract type. Example: [\"firstContract\", \"secondContract\"]")
	public List<String> getContractTypes() {
		return contractTypes;
	}

	public void setContractTypes(List<String> contractTypes) {
		this.contractTypes = contractTypes;
	}

	public FindAbsencesAdvancedIn employees(List<String> employees) {
		this.employees = employees;
		return this;
	}

	public FindAbsencesAdvancedIn addEmployeesItem(String employeesItem) {
		if (this.employees == null) {
			this.employees = new ArrayList<>();
		}
		this.employees.add(employeesItem);
		return this;
	}

	/**
	 * List of employees e-mails or logins. Example:
	 * [\&quot;john.smith@domain.com\&quot;, \&quot;mark.small@domain.com\&quot;]
	 *
	 * @return employees
	 **/
	@Schema(description = "List of employees e-mails or logins. Example: [\"john.smith@domain.com\", \"mark.small@domain.com\"]")
	public List<String> getEmployees() {
		return employees;
	}

	public void setEmployees(List<String> employees) {
		this.employees = employees;
	}

	public FindAbsencesAdvancedIn createdFrom(OffsetDateTime createdFrom) {
		this.createdFrom = createdFrom;
		return this;
	}

	/**
	 * Filter absence requests by date of creation. As a result there will be
	 * absence requests created at the provided moment or later. Please provide the
	 * date and time in ISO 8601 format with time zone.
	 *
	 * @return createdFrom
	 **/
	@Schema(example = "2017-01-23T08:00+01:00", description = "Filter absence requests by date of creation. As a result there will be absence requests created at the provided moment or later. Please provide the date and time in ISO 8601 format with time zone. ")
	public OffsetDateTime getCreatedFrom() {
		return createdFrom;
	}

	public void setCreatedFrom(OffsetDateTime createdFrom) {
		this.createdFrom = createdFrom;
	}

	public FindAbsencesAdvancedIn createdTo(OffsetDateTime createdTo) {
		this.createdTo = createdTo;
		return this;
	}

	/**
	 * Filter absence requests by date of creation. As a result there will be
	 * absence requests created before the provided moment. Please provide the date
	 * and time in ISO 8601 format with time zone.
	 *
	 * @return createdTo
	 **/
	@Schema(example = "2017-01-24T00:00+01:00", description = "Filter absence requests by date of creation. As a result there will be absence requests created before the provided moment. Please provide the date and time in ISO 8601 format with time zone.")
	public OffsetDateTime getCreatedTo() {
		return createdTo;
	}

	public void setCreatedTo(OffsetDateTime createdTo) {
		this.createdTo = createdTo;
	}

	public FindAbsencesAdvancedIn updatedFrom(OffsetDateTime updatedFrom) {
		this.updatedFrom = updatedFrom;
		return this;
	}

	/**
	 * Filter absence requests by date of last update. As a result there will be
	 * absence requests updated at the provided moment or later. Please provide the
	 * date and time in ISO 8601 format with time zone.
	 *
	 * @return updatedFrom
	 **/
	@Schema(example = "2017-01-23T08:00+01:00", description = "Filter absence requests by date of last update. As a result there will be absence requests updated at the provided moment or later. Please provide the date and time in ISO 8601 format with time zone.")
	public OffsetDateTime getUpdatedFrom() {
		return updatedFrom;
	}

	public void setUpdatedFrom(OffsetDateTime updatedFrom) {
		this.updatedFrom = updatedFrom;
	}

	public FindAbsencesAdvancedIn updatedTo(OffsetDateTime updatedTo) {
		this.updatedTo = updatedTo;
		return this;
	}

	/**
	 * Filter absence requests by date of last update. As a result there will be
	 * absence requests updated before the provided moment. Please provide the date
	 * and time in ISO 8601 format with time zone.
	 *
	 * @return updatedTo
	 **/
	@Schema(example = "2017-01-24T00:00+01:00", description = "Filter absence requests by date of last update. As a result there will be absence requests updated before the provided moment. Please provide the date and time in ISO 8601 format with time zone.")
	public OffsetDateTime getUpdatedTo() {
		return updatedTo;
	}

	public void setUpdatedTo(OffsetDateTime updatedTo) {
		this.updatedTo = updatedTo;
	}

	public FindAbsencesAdvancedIn absenceStatuses(List<String> absenceStatuses) {
		this.absenceStatuses = absenceStatuses;
		return this;
	}

	public FindAbsencesAdvancedIn addAbsenceStatusesItem(String absenceStatusesItem) {
		if (this.absenceStatuses == null) {
			this.absenceStatuses = new ArrayList<>();
		}
		this.absenceStatuses.add(absenceStatusesItem);
		return this;
	}

	/**
	 * Filter absence requests by absence statuses. As a result there will be
	 * absence requests with chosen statuses. By default return all absence
	 * requests. Allowed values: [\&quot;PENDING\&quot;,
	 * \&quot;PENDING_CANCELLATION\&quot;, \&quot;REJECTED\&quot;,
	 * \&quot;APPROVED\&quot;, \&quot;CANCELED\&quot;, \&quot;REVOKED\&quot;]
	 *
	 * @return absenceStatuses
	 **/
	@Schema(example = "[PENDING, APPROVED]", description = "Filter absence requests by absence statuses. As a result there will be absence requests with chosen statuses. By default return all absence requests. Allowed values: [\"PENDING\", \"PENDING_CANCELLATION\", \"REJECTED\", \"APPROVED\", \"CANCELED\", \"REVOKED\"]")
	public List<String> getAbsenceStatuses() {
		return absenceStatuses;
	}

	public void setAbsenceStatuses(List<String> absenceStatuses) {
		this.absenceStatuses = absenceStatuses;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FindAbsencesAdvancedIn findAbsencesAdvancedIn = (FindAbsencesAdvancedIn) o;
		return Objects.equals(this.from, findAbsencesAdvancedIn.from)
				&& Objects.equals(this.to, findAbsencesAdvancedIn.to)
				&& Objects.equals(this.absenceTypes, findAbsencesAdvancedIn.absenceTypes)
				&& Objects.equals(this.teams, findAbsencesAdvancedIn.teams)
				&& Objects.equals(this.positions, findAbsencesAdvancedIn.positions)
				&& Objects.equals(this.contractTypes, findAbsencesAdvancedIn.contractTypes)
				&& Objects.equals(this.employees, findAbsencesAdvancedIn.employees)
				&& Objects.equals(this.createdFrom, findAbsencesAdvancedIn.createdFrom)
				&& Objects.equals(this.createdTo, findAbsencesAdvancedIn.createdTo)
				&& Objects.equals(this.updatedFrom, findAbsencesAdvancedIn.updatedFrom)
				&& Objects.equals(this.updatedTo, findAbsencesAdvancedIn.updatedTo)
				&& Objects.equals(this.absenceStatuses, findAbsencesAdvancedIn.absenceStatuses);
	}

	@Override
	public int hashCode() {
		return Objects.hash(from, to, absenceTypes, teams, positions, contractTypes, employees, createdFrom, createdTo,
				updatedFrom, updatedTo, absenceStatuses);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FindAbsencesAdvancedIn {\n");

		sb.append("    from: ").append(toIndentedString(from)).append("\n");
		sb.append("    to: ").append(toIndentedString(to)).append("\n");
		sb.append("    absenceTypes: ").append(toIndentedString(absenceTypes)).append("\n");
		sb.append("    teams: ").append(toIndentedString(teams)).append("\n");
		sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
		sb.append("    contractTypes: ").append(toIndentedString(contractTypes)).append("\n");
		sb.append("    employees: ").append(toIndentedString(employees)).append("\n");
		sb.append("    createdFrom: ").append(toIndentedString(createdFrom)).append("\n");
		sb.append("    createdTo: ").append(toIndentedString(createdTo)).append("\n");
		sb.append("    updatedFrom: ").append(toIndentedString(updatedFrom)).append("\n");
		sb.append("    updatedTo: ").append(toIndentedString(updatedTo)).append("\n");
		sb.append("    absenceStatuses: ").append(toIndentedString(absenceStatuses)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
