/*
 * Calamari API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * Contact: developers@calamari.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.thecodest.slack.holidayreminder.calamari.remote.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDate;
import java.util.Objects;

/**
 * GetBalanceOfEmployeeAndAbsenceType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-06T15:14:15.923389380+02:00[Europe/Warsaw]")
public class GetBalanceOfEmployeeAndAbsenceType {
	@SerializedName("absenceTypeId")
	private String absenceTypeId = null;

	@SerializedName("employee")
	private String employee = null;

	@SerializedName("date")
	private LocalDate date = null;

	public GetBalanceOfEmployeeAndAbsenceType absenceTypeId(String absenceTypeId) {
		this.absenceTypeId = absenceTypeId;
		return this;
	}

	/**
	 * Absence type Id
	 *
	 * @return absenceTypeId
	 **/
	@Schema(example = "PTO", required = true, description = "Absence type Id")
	public String getAbsenceTypeId() {
		return absenceTypeId;
	}

	public void setAbsenceTypeId(String absenceTypeId) {
		this.absenceTypeId = absenceTypeId;
	}

	public GetBalanceOfEmployeeAndAbsenceType employee(String employee) {
		this.employee = employee;
		return this;
	}

	/**
	 * Employee e-mail or login
	 *
	 * @return employee
	 **/
	@Schema(example = "john.white@mycompany.com", required = true, description = "Employee e-mail or login")
	public String getEmployee() {
		return employee;
	}

	public void setEmployee(String employee) {
		this.employee = employee;
	}

	public GetBalanceOfEmployeeAndAbsenceType date(LocalDate date) {
		this.date = date;
		return this;
	}

	/**
	 * Date in ISO format
	 *
	 * @return date
	 **/
	@Schema(example = "Tue Sep 25 02:00:00 CEST 2018", required = true, description = "Date in ISO format")
	public LocalDate getDate() {
		return date;
	}

	public void setDate(LocalDate date) {
		this.date = date;
	}

	@Override
	public boolean equals(Object o) {
		if(this == o) {
			return true;
		}
		if(o == null || getClass() != o.getClass()) {
			return false;
		}
		GetBalanceOfEmployeeAndAbsenceType getBalanceOfEmployeeAndAbsenceType = (GetBalanceOfEmployeeAndAbsenceType) o;
		return Objects.equals(this.absenceTypeId, getBalanceOfEmployeeAndAbsenceType.absenceTypeId) && Objects.equals(this.employee, getBalanceOfEmployeeAndAbsenceType.employee) && Objects.equals(this.date, getBalanceOfEmployeeAndAbsenceType.date);
	}

	@Override
	public int hashCode() {
		return Objects.hash(absenceTypeId, employee, date);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class GetBalanceOfEmployeeAndAbsenceType {\n");

		sb.append("    absenceTypeId: ").append(toIndentedString(absenceTypeId)).append("\n");
		sb.append("    employee: ").append(toIndentedString(employee)).append("\n");
		sb.append("    date: ").append(toIndentedString(date)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if(o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
