/*
 * Calamari API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * Contact: developers@calamari.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.thecodest.slack.holidayreminder.calamari.remote.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * LocalTime
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-06T15:14:15.923389380+02:00[Europe/Warsaw]")
public class LocalTime {
	@SerializedName("chronology")
	private Chronology chronology = null;

	@SerializedName("millisOfDay")
	private Integer millisOfDay = null;

	@SerializedName("hourOfDay")
	private Integer hourOfDay = null;

	@SerializedName("minuteOfHour")
	private Integer minuteOfHour = null;

	@SerializedName("secondOfMinute")
	private Integer secondOfMinute = null;

	@SerializedName("millisOfSecond")
	private Integer millisOfSecond = null;

	@SerializedName("fields")
	private List<DateTimeField> fields = null;

	@SerializedName("values")
	private List<Integer> values = null;

	@SerializedName("fieldTypes")
	private List<DateTimeFieldType> fieldTypes = null;

	public LocalTime chronology(Chronology chronology) {
		this.chronology = chronology;
		return this;
	}

	/**
	 * Get chronology
	 *
	 * @return chronology
	 **/
	@Schema(description = "")
	public Chronology getChronology() {
		return chronology;
	}

	public void setChronology(Chronology chronology) {
		this.chronology = chronology;
	}

	public LocalTime millisOfDay(Integer millisOfDay) {
		this.millisOfDay = millisOfDay;
		return this;
	}

	/**
	 * Get millisOfDay
	 *
	 * @return millisOfDay
	 **/
	@Schema(description = "")
	public Integer getMillisOfDay() {
		return millisOfDay;
	}

	public void setMillisOfDay(Integer millisOfDay) {
		this.millisOfDay = millisOfDay;
	}

	public LocalTime hourOfDay(Integer hourOfDay) {
		this.hourOfDay = hourOfDay;
		return this;
	}

	/**
	 * Get hourOfDay
	 *
	 * @return hourOfDay
	 **/
	@Schema(description = "")
	public Integer getHourOfDay() {
		return hourOfDay;
	}

	public void setHourOfDay(Integer hourOfDay) {
		this.hourOfDay = hourOfDay;
	}

	public LocalTime minuteOfHour(Integer minuteOfHour) {
		this.minuteOfHour = minuteOfHour;
		return this;
	}

	/**
	 * Get minuteOfHour
	 *
	 * @return minuteOfHour
	 **/
	@Schema(description = "")
	public Integer getMinuteOfHour() {
		return minuteOfHour;
	}

	public void setMinuteOfHour(Integer minuteOfHour) {
		this.minuteOfHour = minuteOfHour;
	}

	public LocalTime secondOfMinute(Integer secondOfMinute) {
		this.secondOfMinute = secondOfMinute;
		return this;
	}

	/**
	 * Get secondOfMinute
	 *
	 * @return secondOfMinute
	 **/
	@Schema(description = "")
	public Integer getSecondOfMinute() {
		return secondOfMinute;
	}

	public void setSecondOfMinute(Integer secondOfMinute) {
		this.secondOfMinute = secondOfMinute;
	}

	public LocalTime millisOfSecond(Integer millisOfSecond) {
		this.millisOfSecond = millisOfSecond;
		return this;
	}

	/**
	 * Get millisOfSecond
	 *
	 * @return millisOfSecond
	 **/
	@Schema(description = "")
	public Integer getMillisOfSecond() {
		return millisOfSecond;
	}

	public void setMillisOfSecond(Integer millisOfSecond) {
		this.millisOfSecond = millisOfSecond;
	}

	public LocalTime fields(List<DateTimeField> fields) {
		this.fields = fields;
		return this;
	}

	public LocalTime addFieldsItem(DateTimeField fieldsItem) {
		if(this.fields == null) {
			this.fields = new ArrayList<>();
		}
		this.fields.add(fieldsItem);
		return this;
	}

	/**
	 * Get fields
	 *
	 * @return fields
	 **/
	@Schema(description = "")
	public List<DateTimeField> getFields() {
		return fields;
	}

	public void setFields(List<DateTimeField> fields) {
		this.fields = fields;
	}

	public LocalTime values(List<Integer> values) {
		this.values = values;
		return this;
	}

	public LocalTime addValuesItem(Integer valuesItem) {
		if(this.values == null) {
			this.values = new ArrayList<>();
		}
		this.values.add(valuesItem);
		return this;
	}

	/**
	 * Get values
	 *
	 * @return values
	 **/
	@Schema(description = "")
	public List<Integer> getValues() {
		return values;
	}

	public void setValues(List<Integer> values) {
		this.values = values;
	}

	public LocalTime fieldTypes(List<DateTimeFieldType> fieldTypes) {
		this.fieldTypes = fieldTypes;
		return this;
	}

	public LocalTime addFieldTypesItem(DateTimeFieldType fieldTypesItem) {
		if(this.fieldTypes == null) {
			this.fieldTypes = new ArrayList<>();
		}
		this.fieldTypes.add(fieldTypesItem);
		return this;
	}

	/**
	 * Get fieldTypes
	 *
	 * @return fieldTypes
	 **/
	@Schema(description = "")
	public List<DateTimeFieldType> getFieldTypes() {
		return fieldTypes;
	}

	public void setFieldTypes(List<DateTimeFieldType> fieldTypes) {
		this.fieldTypes = fieldTypes;
	}

	@Override
	public boolean equals(Object o) {
		if(this == o) {
			return true;
		}
		if(o == null || getClass() != o.getClass()) {
			return false;
		}
		LocalTime localTime = (LocalTime) o;
		return Objects.equals(this.chronology, localTime.chronology) && Objects.equals(this.millisOfDay, localTime.millisOfDay) && Objects.equals(this.hourOfDay, localTime.hourOfDay) && Objects.equals(this.minuteOfHour, localTime.minuteOfHour) && Objects.equals(this.secondOfMinute, localTime.secondOfMinute) && Objects.equals(this.millisOfSecond, localTime.millisOfSecond) && Objects.equals(this.fields, localTime.fields) && Objects.equals(this.values, localTime.values) && Objects.equals(this.fieldTypes, localTime.fieldTypes);
	}

	@Override
	public int hashCode() {
		return Objects.hash(chronology, millisOfDay, hourOfDay, minuteOfHour, secondOfMinute, millisOfSecond, fields, values, fieldTypes);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class LocalTime {\n");

		sb.append("    chronology: ").append(toIndentedString(chronology)).append("\n");
		sb.append("    millisOfDay: ").append(toIndentedString(millisOfDay)).append("\n");
		sb.append("    hourOfDay: ").append(toIndentedString(hourOfDay)).append("\n");
		sb.append("    minuteOfHour: ").append(toIndentedString(minuteOfHour)).append("\n");
		sb.append("    secondOfMinute: ").append(toIndentedString(secondOfMinute)).append("\n");
		sb.append("    millisOfSecond: ").append(toIndentedString(millisOfSecond)).append("\n");
		sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
		sb.append("    values: ").append(toIndentedString(values)).append("\n");
		sb.append("    fieldTypes: ").append(toIndentedString(fieldTypes)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if(o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
