/*
 * Calamari API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * Contact: developers@calamari.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.thecodest.slack.holidayreminder.calamari.remote.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * TimeZone
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-06T15:14:15.923389380+02:00[Europe/Warsaw]")
public class TimeZone {
	@SerializedName("displayName")
	private String displayName = null;

	@SerializedName("id")
	private String id = null;

	@SerializedName("dstsavings")
	private Integer dstsavings = null;

	@SerializedName("rawOffset")
	private Integer rawOffset = null;

	public TimeZone displayName(String displayName) {
		this.displayName = displayName;
		return this;
	}

	/**
	 * Get displayName
	 *
	 * @return displayName
	 **/
	@Schema(description = "")
	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public TimeZone id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * Get id
	 *
	 * @return id
	 **/
	@Schema(description = "")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TimeZone dstsavings(Integer dstsavings) {
		this.dstsavings = dstsavings;
		return this;
	}

	/**
	 * Get dstsavings
	 *
	 * @return dstsavings
	 **/
	@Schema(description = "")
	public Integer getDstsavings() {
		return dstsavings;
	}

	public void setDstsavings(Integer dstsavings) {
		this.dstsavings = dstsavings;
	}

	public TimeZone rawOffset(Integer rawOffset) {
		this.rawOffset = rawOffset;
		return this;
	}

	/**
	 * Get rawOffset
	 *
	 * @return rawOffset
	 **/
	@Schema(description = "")
	public Integer getRawOffset() {
		return rawOffset;
	}

	public void setRawOffset(Integer rawOffset) {
		this.rawOffset = rawOffset;
	}

	@Override
	public boolean equals(Object o) {
		if(this == o) {
			return true;
		}
		if(o == null || getClass() != o.getClass()) {
			return false;
		}
		TimeZone timeZone = (TimeZone) o;
		return Objects.equals(this.displayName, timeZone.displayName) && Objects.equals(this.id, timeZone.id) && Objects.equals(this.dstsavings, timeZone.dstsavings) && Objects.equals(this.rawOffset, timeZone.rawOffset);
	}

	@Override
	public int hashCode() {
		return Objects.hash(displayName, id, dstsavings, rawOffset);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class TimeZone {\n");

		sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    dstsavings: ").append(toIndentedString(dstsavings)).append("\n");
		sb.append("    rawOffset: ").append(toIndentedString(rawOffset)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if(o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
