/*
 * Calamari API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * Contact: developers@calamari.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.thecodest.slack.holidayreminder.calamari.remote.api.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * WorkingWeekOut
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-06T15:14:15.923389380+02:00[Europe/Warsaw]")
public class WorkingWeekOut {
	@SerializedName("id")
	private Long id = null;

	@SerializedName("name")
	private String name = null;

	@SerializedName("workingDays")
	private List<WorkingDay> workingDays = new ArrayList<>();

	public WorkingWeekOut id(Long id) {
		this.id = id;
		return this;
	}

	/**
	 * Working week id.
	 *
	 * @return id
	 **/
	@Schema(example = "1", required = true, description = "Working week id.")
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public WorkingWeekOut name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * Working week name.
	 *
	 * @return name
	 **/
	@Schema(example = "Full time", required = true, description = "Working week name.")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public WorkingWeekOut workingDays(List<WorkingDay> workingDays) {
		this.workingDays = workingDays;
		return this;
	}

	public WorkingWeekOut addWorkingDaysItem(WorkingDay workingDaysItem) {
		this.workingDays.add(workingDaysItem);
		return this;
	}

	/**
	 * Working week days.
	 *
	 * @return workingDays
	 **/
	@Schema(required = true, description = "Working week days.")
	public List<WorkingDay> getWorkingDays() {
		return workingDays;
	}

	public void setWorkingDays(List<WorkingDay> workingDays) {
		this.workingDays = workingDays;
	}

	@Override
	public boolean equals(Object o) {
		if(this == o) {
			return true;
		}
		if(o == null || getClass() != o.getClass()) {
			return false;
		}
		WorkingWeekOut workingWeekOut = (WorkingWeekOut) o;
		return Objects.equals(this.id, workingWeekOut.id) && Objects.equals(this.name, workingWeekOut.name) && Objects.equals(this.workingDays, workingWeekOut.workingDays);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, name, workingDays);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class WorkingWeekOut {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    workingDays: ").append(toIndentedString(workingDays)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(Object o) {
		if(o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
