/*
 * Calamari API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * Contact: developers@calamari.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.thecodest.slack.holidayreminder.calamari.remote;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-06T15:14:15.923389380+02:00[Europe/Warsaw]")
public class Pair {
	private String name = "";
	private String value = "";

	public Pair(String name, String value) {
		setName(name);
		setValue(value);
	}

	public String getName() {
		return this.name;
	}

	private void setName(String name) {
		if(!isValidString(name))
			return;

		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	private void setValue(String value) {
		if(!isValidString(value))
			return;

		this.value = value;
	}

	private boolean isValidString(String arg) {
		if(arg == null)
			return false;
		if(arg.trim().isEmpty())
			return false;

		return true;
	}
}
