name: Build & deploy to staging

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
